### ISSUE TITLE
feat: Mount CometBFT chain RPC on a subpath of the user RPC

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#1000]
In an attempt to reduce the complexity of Kwil, we should explore the possibility of mounting the CometBFT RPC on a subpath of the user RPC. It's not immediately clear to users who are not familiar with Tendermint why these are different, and makes it more complex to configure Kwil.

It's not critical if we can't do this / if it is hard to accomplish, but we should explore it since it would be nice.

**Comment by jchappelow** [comment]
Almost done actually
