### ISSUE TITLE
statesync should error before applying a snapshot if the DB is already populated

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#1001]
`2024-09-19T17:39:42.143Z        error   kwild.cometbft  node/setup.go:521       State sync failed       {"module": "statesync", "err": "snapshot restoration failed: 
failed to apply chunk 0: dataset exists: x00467feba5d3998a7550816403e01809fe5243f6a989236f3bd0caac", "goversion": "go1.23.1", "mod_version": "(devel)", "revision": "beeaca90b2000cbb9a10873803bc48e319db218f", "build_time": "2024-09-19T12:07:00Z", "dirty": true}`

**Comment by brennanjl** [comment]
@charithabandi I know we discussed doing this last week. Did you end up adding this? Just trying to avoid doing double work on this issue.
