### ISSUE TITLE
config naming discrepency

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#1009]
We currently have these two configurations: `app.snapshots.enabled`, and `chain.statesync.enable`. We should reconcile these, such that they are both either `enable` or `enabled`. The one that is broken should get deprecated.

**Comment by brennanjl** [comment]
I definitely agree that these are distinct. I am just irked by one being past tensed (`enabled`), while another is present tense (`enable`). Just looks sloppy imo

**Comment by jchappelow** [comment]
Oh the actually spelling!  Gotcha
