### ISSUE TITLE
get CI and all build scripts using Go workspace mode so we never need replaces in go.mod

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#1048]
Go workspace mode supposedly makes it so we don't ever need to do this `replace` dance in `go.mod` files.  However we still have CI and build scripts that bounce in and out of `GOWORK` mode.  Ideally we should get everything working with just a correct `go.work` and never need to add in `replace` statements to `go.mod` during development.

See https://go.dev/blog/get-familiar-with-workspaces and https://go.dev/doc/tutorial/workspaces.  These are somewhat outdated, but the motivation is there.

**Comment by brennanjl** [comment]
Should we try this for this release?

**Comment by jchappelow** [comment]
We would always want go.mod to have no `replace`, so what we could try is to address this issue after we release so that we don't have to *add them back in*.  So, yes, after we tag with no replaces, we should try to get everything working in workspace mode so we don't have to add them back.
