### ISSUE TITLE
make @block_timestamp available in action call

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kwil-db#1084]
Right now @block_timestamp is only available in TX, but action/procedure call.

Since we've already save the timestamp in block header, we can set the timestamp from the latest block when action/procedure call.

This is realated to #903. I'm not sure if there is a reason we didn't make it available in action/procedure call

**Comment by brennanjl** [comment]
Fix is here: https://github.com/kwilteam/kwil-db/pull/1088
