### ISSUE TITLE
Bug: GossipSub doesn't work if followers are started before leader

### ISSUE THREAD

**Issue by charithabandi** [kwilteam/kwil-db#1135]
### Version / Commit

v0.10.0 (prerelease)

### Operating System

any

### Configuration

./kwild setup testnet -v 2

### Expected Behavior

order of bring up shouldn't matter

### Actual Behavior

Network is stuck if followers are launched before leader as they don't receive the discovery requests (which is used by the leader to guage the network height)

### Steps to Reproduce

```
./kwild setup testnet -v 2

# start follower
./kwild -r .testnet/node1

# start leader
./kwild -r .testnet/node0
```

**Comment by jchappelow** [comment]
This only happens at genesis (before first comment.  So, I realized this is just a consequence of setup testnet and now the leader's bootnodes is empty.  There's also a minor bug where if the bootnode connect fails (which is what is happening on validator that starts first), it is not added to the address book AFAICT.

Will resolve and ensure that's all it is.
