### ISSUE TITLE
Feature Request: Kwil-admin commands support

### ISSUE THREAD

**Issue by charithabandi** [kwilteam/kwil-db#1145]
Just a placeholder to track the previous kwil-admin commands

`Validators:`
- [x] Approve
- [x] Leave
- [x] Remove
- [x] List
- [x] JoinStatus

`Admin`:

- [x] `dump-cfg`
- [x] `version`
- [x] `status`
- [x] `peers`
- [x] `gen-auth-key`

`Peers:`(related to peer filtering) @jchappelow  is working on this
- [x] Add
- [x] Remove
- [x] List

`Snapshot:`
- [x]  Create

`Migration:`(not a priority unless we support zdt)
- [ ] Propose
- [ ] Approve
- [ ] List
- [ ] ProposalStatus
- [ ] MigrationStatus
- [ ] GenesisState

**Comment by jchappelow** [comment]
I'm working on the peers commands with https://github.com/kwilteam/kwil-db/issues/1143

Also status-via-rpc command, tentatively `kwild status` but maybe a new subcommand
