### ISSUE TITLE
HTTP api `byte` encoding

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kwil-db#285]
This pr tries to bring up concerns on inconsistencies of `byte` filed across Kwil.

By default, json will use base64 for `byte` fileds.  But there are some `byte` fileds by convention, are commonly represented as HEX, for example `hash`, and that's what we do.

This actually leads to some wrong pratices because we don't have a guidance on existing fields encoding, for example, when logging, should i using base64 or HEX?

And after discussion, we sort of agree on those fields should be displayed as HEX (in any output, logs):
- `TxHash`
- `PublicKey`
This is good enough to guide us, at least for example, logging.

There is still room for confusion.  For example, the output from HTTP api directly and from SDK will be different, since SDK will convert some filed to HEX.  

A question mark for near future: we'll need a blockchain explorer, what the encoding are we going to use for `byte` filed for transaction info to display?  Are we going to keep same like right now to keep consistent with HTTP api?  It doesn't make too much sense to me to see a Tx info with some filed as HEX and some as base64.

**Comment by jchappelow** [comment]
Resolved and mostly obsoleted by JSON-RPC
