### ISSUE TITLE
use `errors.Join` in antlr parser

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kwil-db#292]
since go 1.20, there is a new function `errors.Join`, which could replace our crafted `ErrorList`.

This `ErrorList` is used in multiple places:
- sqlparser
- actparser
- Kuneiform

By changing this, some error compare methods could also be changed.

**Comment by jchappelow** [comment]
Resolved in a different manner in https://github.com/kwilteam/kwil-db/pull/698
