### ISSUE TITLE
concerns about DBID and re-deploy

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kwil-db#332]
At first I was only thinking in a certain use case that I wanted to cache Schema, realizing the DBID derivation schema makes it hard.

As I start to think what this concern is really about, I realize it is related to how we should do migration/upgrade in Kwil, for this I don't have an answer yet.  
This may not be an issue depends on how we envision Kwil, open for discussion.

Currently DBID is derived from `dbName` and `deployerPublicKey`, as long as the same wallet deploy the Kuneiform(will use KF thereafter) with same database name, the DBID is same.     This alone is no big deal, only it makes cache schema not easy.

And we currently also support `re-deploy`, so if you use the same database name, the DBID will be same, no matter what changes you make to the KF file(tables, actions may change).  I think `re-deploy` is really the concern.
 
Image there are a KF called web3-user, a 3rd party KF called web3-X (using web3-user), and a 3rd party frontend interact with web3-user.  

If web3-user got re-deployed, with some actions' input and output changed:
- this 3rd party KF web3-x may break
- this 3rd frontend may break

This might not be an issue for POA blockchain(consider it as a DAPP), since the blockchain as a whole serves as backend, this DAPP can always schedule a upgrade to make sure everything works, but still there will be issues if there are apps(or partners) build on top of it.

I think the ability of `re-deploy` should be  `migration`(about underlying database)  + `upgrade`(about actions), because normally you would change your SQL queries more often than tables.  @brennanjl made a point that if you `migration`, you probably will change actions, that's true.
But even with `migration/upgrade`, the problems above still exist, so I guess allow `re-deploy` is NBD.

Another problem regarding upgrade is security, this is true to all smart contract platforms, a general best practice is to use multisign wallet + voting to make sure a legit upgrade.

**Comment by brennanjl** [comment]
Closing since this is a year old and it doesn't seem like anything we would do any time soon
