### ISSUE TITLE
Bug: `kwild` postgres flags use underscores, should use hyphens

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#514]
`kwild`'s flags for configuring Postgres (such as `--app.pg_db_host`) use underscores, and should use hyphens. This should get fixed before release.

**Comment by charithabandi** [comment]
![Screenshot 2024-02-27 at 2 17 35 PM](https://github.com/kwilteam/kwil-db/assets/45089429/43590cc3-aa2c-4dcb-86f5-21985c0f5ed6)

Looks to be fixed. Closing it.
