### ISSUE TITLE
initchain should perform some sanity checks to ensure PG / stores are fresh

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#521]
`(*TxApp) GenesisInit` is called at genesis only, and seems to be an appropriate place to ensure that the postgres database does not have tables left over from a previous reset instance (just the internal stores, not user datasets that we may want at genesis).

Other places this could be checked instead?  Before starting, in `buildServer`, use ABCI's metadata store to determine if height>0 and if so require 0 validators known by voting store?

**Comment by charithabandi** [comment]
What about the scenarios where network starts with a pre-existing data? How would u ensure this?

**Comment by jchappelow** [comment]
In spirit, the same functionality that you had previously implemented with `PatchGenesisAppHash` for existing SQLite datasets.  The mechanism would have to change of course since we can't just hash .sqlite files anymore.

**Comment by jchappelow** [comment]
We just chatted about a related issue, which is that `kwil-admin setup genesis-hash` has no direct analogy, so for 0.7.0 we should disable / hide that command and remove `PatchGenesisAppHash` and all the related sqlite file code.

To make that functionality available, it would probably be something like:

- list datasets (pg schemas with "ds_" prefix)
- list all tables a dataset (either using engine's knowledge of schema and the ddl _or_ using postgresql queryes e.g. `SELECT table_name FROM information_schema.tables WHERE table_schema = 'your_schema_name' ORDER BY table_name;`)
- `select * ` from each table and has *everything*

Not sure if this is overkill or the only option.  We cannot simply hash the files stored by postgresql as we could with sqlite. Right?

**Comment by jchappelow** [comment]
@charithabandi I'm fiddling with a new method for genesis has.  Please feel free to do the initial validators check tho

**Comment by charithabandi** [comment]
Previously we didn't had a distinction between internal and user data, however now when we talk about genesis data, don't we have to include the internal schemas too like accounts and others? and different schemas are treated differently here. Like accounts can be consumed as is, but not vote store bcz we might have different genesis validators??

**Comment by jchappelow** [comment]
I think accounts and voting stores, anything other than user datasets and the schemas meta data table should be empty.

We have genesis allocs to do account credits and genesis, and the validators list in genesis.json as well.

**Comment by jchappelow** [comment]
I started thinking though how we'd go about digesting the datasets like we were previously doing a sha256 hash of the sqlite files.  It's not as straightforward, plus as you mentioned @charithabandi we would really want to have the `kwil_accounts` persisted.

We can get a fair bit done with the engine hiding the `kwil_internal.kwil_schemas` details, but we eventually get to a point where we have to iterate through the columns in a deterministic way and I don't quite know what's next.

```
func PatchGenesisAppHash(ctx context.Context, cfg *pg.ConnConfig, genesisFile string) ([]byte, error) {
	conns, err := pg.NewPool(ctx, &pg.PoolConfig{
		ConnConfig: *cfg,
		MaxConns:   2,
	})
	if err != nil {
		return nil, err
	}

	engineCtx, err := execution.NewGlobalContext(ctx, conns, map[string]actions.ExtensionInitializer{}, nil)
	if err != nil {
		return nil, err
	}

	datasets, err := engineCtx.ListDatasets(ctx, nil)
	if err != nil {
		return nil, err
	}

	for _, dataset := range datasets {
		schema, err := engineCtx.GetSchema(ctx, dataset.DBID)
		if err != nil {
			return nil, err
		}
		pgSchema := execution.DBIDSchema(dataset.DBID)
		for _, table := range schema.Tables {
			qualifiedTableName := pgSchema + "." + table.Name
			// HERE we need to iterate over all the columns in a deterministic way to form a digest of all the data.

			...
		}
	}

	// ALSO, we should probably migrate and digest the accounts table.
	...


```

**Comment by jchappelow** [comment]
And then the related challenge is how to actually move the required data over to a new postgres cluster.

I feel like we need to spec out a concept of operations, starting from the scenario where you'd want to lose all of your blockchain transactions but keep the datasets (and accounts), describe how to get that data into some export file, and then how the `kwil-admin genesis-hash` function should work and with what postgres cluster (old or new with imported data).

For 0.7.0, I think we should hid this genesis-hash function and just error out if there's existing validators in a `voters` table, which means we're about to do a `GenesisInit`, which inserts the genesis validators, but they have already been inserted from a previous install.

Thoughts in general about the need to do a migration with a reset to genesis, and how someone would want to execute on it?

**Comment by jchappelow** [comment]
Perhaps if the genesis.json file has a non-null `"app_hash"` then we require both `"validators"` and `"alloc"` to be null, because this would mean that we are carrying over these tables?  Or just for accounts perhaps?  It depends if we can/should carry over the `kwil_voting` tables or just `kwil_accounts`...

**Comment by jchappelow** [comment]
Yeah, I really need more context on the use case for restarting a chain with existing data/accounts.  :laughing:   I used to think the initial data concept was for deployments that simply wanted to bootstrap with schemas and some foundational data.  But I guess we're trying to accommodate starting fresh from a previous long running chain...
Not sure how best to proceed other then to detect and halt if it's not fresh for 0.7.0.
