### ISSUE TITLE
impossible error in (*OracleMgr).Start, no errors from oracles.OracleFunc

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#577]
This error cannot be hit:

https://github.com/kwilteam/kwil-db/blob/c6a411c63e89927b137f3b2e20242bab04156db5/internal/oracles/mgr.go#L103-L105

Looking at the registered `OracleFunc`s, I also see no error return, but then there are a lot of unhandled errors and questionable conditions in the eth deposit oracle: https://github.com/kwilteam/kwil-db/blob/c6a411c63e89927b137f3b2e20242bab04156db5/extensions/oracles/eth_deposits/deposits.go#L39-L47

That runs as a goroutine, so that kinda makes sense, but you might not notice that it didn't start, or started with the incorrect configuration.

**Comment by brennanjl** [comment]
Oh that error is a remnant of when the oracle function did return an error. It can simply be removed

**Comment by brennanjl** [comment]
regarding the eth deposit oracle, I think that was just not updated properly after changing the oracle function signature. Will handle now

**Comment by jchappelow** [comment]
For instance, how is appropriate to handle the many possible errors in https://github.com/kwilteam/kwil-db/blob/c6a411c63e89927b137f3b2e20242bab04156db5/extensions/oracles/eth_deposits/deposits.go#L39-L47?
Can return them or can panic etc.

**Comment by charithabandi** [comment]
https://github.com/kwilteam/kwil-db/compare/oracles-start?expand=1 How about something like this?

**Comment by brennanjl** [comment]
They should be logged and then just return.

I didn't really want it to return an error because there is no way for us to handle the error. By not accepting a returned error, I think it is clear to the implementer that they should be very diligent in handling errors. This is particularly important for an oracle, where transient errors are the most common.

**Comment by brennanjl** [comment]
Resolved in: https://github.com/kwilteam/kwil-db/pull/586

**Comment by brennanjl** [comment]
I sort've assumed that Kwild would start without the oracle running, yeah. I guess I can see why this may not be ideal. Do you think we should add the error?

**Comment by jchappelow** [comment]
The way I see it is that if the config.toml defines and oracle and it's config, but it fails to start, the operator would want to know, because if it didn't start, then they are running in an unintended state.

**Comment by brennanjl** [comment]
Ok that makes sense. So I guess we allow them to return errors, but make it clear that an error returned will shut down the node?

**Comment by jchappelow** [comment]
Maybe I'm seeing this differently, but I would think it would be implied that if your oracle function returns and error it would be the way your oracle extension asserts that it is not ready (or configured correctly) and needs to be fixed.   I'd be pretty frustrated if I entered the wrong api key or hostname for an RPC provider etc. and kwild just ran without stopping me to fix it.
The oracle may be optional, and if I couldn't fix the config or the pathological state that broke the oracle, I would comment out the config to proceed.

**Comment by brennanjl** [comment]
Ok, I think I have a happy-medium here: https://github.com/kwilteam/kwil-db/pull/586
