### ISSUE TITLE
Improve KGW error messages

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#643]
If I run kgw without the --allow-deploy-db flag, and try to deploy a database, I get failed to deploy database: invalid character 'F' looking for beginning of value. This is because it is returning a `403 Forbidden`. We should correctly read out the error.

**Comment by Yaiba** [comment]
duplicate with kwilteam/kgw#17

**Comment by jchappelow** [comment]
The client on main is more robust to this.

This should be on `release-v0.6`: https://github.com/kwilteam/kwil-db/commit/231926f8dd3ee2669af32d5cd78a98abcb5a5095

**Comment by Yaiba** [comment]
For kgw, Fixes has been backported to v0.1.4 and v0.2.1.

For kwil-cli,
- v0.7 is able to parser it accordingly, no changes are made for this issue.
- v0.6 is fixed by backport #507 and #624

Consider fixed.
