### ISSUE TITLE
Problem: Confusing error message when a user has no gas

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kwil-db#653]
On networks that require gas, if a user (with a balance = 0) tries to execute something that requires gas (deploy db, drop db, etc) kwil-db returns the error: account their_address does not exist.

I assume this is because the account is not in the accounts table; however, it is a confusing error (especially because it is the first error most people get with Kwil). When a user tries to execute something that requires gas and does not have enough, the error should be something like: "Insufficient balance."

**Comment by jchappelow** [comment]
I have been mulling this over.  This will be addresses in JSON-RPC's overhauled error codes and improved error handling capabilities.  However what's not obvious to me is that "insufficient balance" is right in all cases for an account that has never interacted with a Kwil chain.  I think there's precedent for that approach, but I'm not totally certain it's best.

**Comment by jchappelow** [comment]
If everyone hits this when trying to do their first mutable action, and they don't immediately realize they need funds to do something, I agree the response to execution when an account does not exists and gas is required it should say something about acquiring funds.

Will have a look at where in tx app or possibly the rpc service this might be addressed.
