### ISSUE TITLE
Feature Request: add a way to configure `defaultConfigFile` from an ENV var

### ISSUE THREAD

**Issue by pkoch** [kwilteam/kwil-db#660]
### Describe the Feature

Having the ability to store some flags for `kwil-cli` in a config file is great. It'd be great if I could have this mechanism _and_, in addition, be able to do something like `KWIL_CLI_CONFIG_FILE="$HOME/.kwil-cli/config.something.json" kwil-cli database query --name mycooldb 'select * from table'`.

However, I do use a lot of deployments, and I have to keep changing between them. Here's my gimmick to cope with that:
```bash
$ ls -pal ~/.kwil_cli/
total 24
drwxr-xr-x. 1 pkoch pkoch  206 abr 13 14:24 ./
drwx------. 1 pkoch pkoch 2020 abr 13 14:10 ../
lrwxrwxrwx. 1 pkoch pkoch   22 abr 13 14:24 config.json -> config.playground.json
-rw-r--r--. 1 pkoch pkoch  130 nov 17 18:48 config.local.json
-rw-r--r--. 1 pkoch pkoch  167 abr  8 21:34 config.playground.json
-rw-r--r--. 1 pkoch pkoch  142 abr  9 15:46 config.production.json
-rw-r--r--. 1 pkoch pkoch  164 abr  8 20:19 config.staging.json
-rwxr-xr-x. 1 pkoch pkoch  195 abr 13 14:06 switch_to.sh

$ cat ~/.kwil_cli/switch_to.sh 
#!/usr/bin/env bash

set -ueo pipefail
cd "$(dirname "${0}")"

TARGET_FILE="$1"

if [ ! -f "$TARGET_FILE" ]; then
  echo >&2 "No file $TARGET_FILE"
  exit 1
fi

ln -sf "$TARGET_FILE" config.json
```

This is not too bad. It does help me a good bit, but it does hamper my ability to copy-paste what I ran into Slack to keep a precise record of the operations I do on my deployed nodes. Furthermore, if I'm doing work mostly on a specific env but want to run a one-off query in another env, I have to do a whole dance of calling `switch_to.sh`.

There's clearly a bigger concept here of config sets, but I'm trying to avoid that on purpose, since I don't really think I'd value that new concept all that much. Perhaps a similar enough step in that direction would be to be able to read `defaultConfigFileName` from the env. I've only realized that while writing this.

Other folks in my team are more keen on always passing in all the flags, but that makes us routinely leak private keys into Slack. Not the end of the world, but certainly something I'm very keen on discouraging. It would be a much bigger deal if we happen to do that in a communication channel with people we can't count on trusting.

### Example Implementation

Here's a dumb first take on it:

```diff
diff --git a/cmd/kwil-cli/config/flags.go b/cmd/kwil-cli/config/flags.go
index 6eb64970..2a8a9732 100644
--- a/cmd/kwil-cli/config/flags.go
+++ b/cmd/kwil-cli/config/flags.go
@@ -46,6 +46,11 @@ func init() {
 	configPath := filepath.Join(dirname, defaultConfigDirName)
 	DefaultConfigDir = configPath
 	defaultConfigFile = filepath.Join(configPath, defaultConfigFileName)
+
+	configFile, present := os.LookupEnv("KWIL_CLI_CONFIG_FILE")
+	if !present {
+		defaultConfigFile = configFile
+	}
 }
 
 func BindGlobalFlags(fs *pflag.FlagSet) {
```

**Comment by jchappelow** [comment]
100% behind a config file flag.

Here's my .kwil_cli folder:

```
$  ll ~/.kwil_cli/
total 40
drwxr-xr-x  2 jon jon 4096 Feb 21 18:17 ./
drwxr-x--- 73 jon jon 4096 Apr 10 18:34 ../
-rw-r--r--  1 jon jon 1519 Apr 10 12:06 auth.json
-rw-r--r--  1 jon jon  151 Mar 26 16:28 config.json
-rw-r--r--  1 jon jon  170 Feb 21 18:17 config.json.7ff
-rw-r--r--  1 jon jon  131 Oct 20 13:37 config.json.bak
-rw-r--r--  1 jon jon  151 Nov 27 14:18 config.json.dc8
-rw-r--r--  1 jon jon  151 Feb 20 10:39 config.json.faucet
-rw-r--r--  1 jon jon  144 Nov 21 16:18 config.json.other
-rw-r--r--  1 jon jon  151 Dec  6 11:40 config.json.x
```

:rofl:

**Comment by jchappelow** [comment]
I'm adding this to the 0.8 milestone.  No assignee yet.  But IMO the resolution it to create a `-c` / `--config` flag that tells kwil-cli what config file to load.  We can support an environment variable assignment, but any setting needs corresponding flags (but obviously not a config file field in this case).

**Comment by jchappelow** [comment]
@pkoch We have a `--config` flag now.  Will be in the 0.8.0 release.
No environment variables for kwil-cli config (pretty sure), but that can be a mini project if need be.
