### ISSUE TITLE
Bug: declaring a config field with environment variable is not working

### ISSUE THREAD

**Issue by outerlook** [kwilteam/kwil-db#701]
### Version / Commit

v0.7.3

### Operating System

Ubuntu 22.04.4 LTS

### Configuration

I'd like to configure just one field using env variables, in this case:

```
[chain.p2p]
external_address = <this one>
```

I used this env variable to configure it:
```
KWILD_CHAIN_P2P_EXTERNAL_ADDRESS=kwil-node-1:2656
```

### Expected Behavior

I'd expect the config to be populated with the env string.

### Actual Behavior

config is not picked up

### Steps to Reproduce

1. setup any server with some custom value for `KWILD_CHAIN_P2P_EXTERNAL_ADDRESS`
2. in debug mode, put a breakpoint at https://github.com/kwilteam/kwil-db/blob/main/cmd/kwild/config/config.go#L346
3. see that the config didn't use it and `envConfig` is in an empty state.

![image](https://github.com/kwilteam/kwil-db/assets/12937160/5964ae15-6b39-4d3e-b831-f5f39c131ebd)
3. see that the config didn't use it and `envConfig` is in an empty state.

### Additional Information

Or did I pick something wrong from the [docs](https://docs.kwil.com/docs/daemon/config/settings#config-override)? Not to be discarded :sweat_smile: 

Another note is that only one level of the configuration structure seems unmarshalled by `viper`.
It looks for `KWILD_ROOTDIR,` `KWILD_APP,` `KWILD_CHAIN,` and `KWILD_LOG`, then stops. 

It is not urgent, as it has workarounds.

**Comment by brennanjl** [comment]
Thanks for bringing this up! cc @charithabandi
