### ISSUE TITLE
Documentation: Missing Gateway Client Documentation

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#704]
The Truflation team noted that they struggled to use the gateway client, as it did not have documentation: https://github.com/truflation/tsn-data-provider/issues/79.

This would just need to include documentation on authentication, how cookies can be read, and control flow.

**Comment by jchappelow** [comment]
I still can't see their repo.

**Comment by brennanjl** [comment]
Just pinged them about that again

**Comment by Yaiba** [comment]
Do we need docs on v0.7?  #742 has docs on v0.8

**Comment by Yaiba** [comment]
@brennanjl question for you hh

**Comment by brennanjl** [comment]
Correct we do not need docs for v07
