### ISSUE TITLE
Bug: kwil-cli provider config

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#709]
I have noticed an issue when trying to use `kwil-cli`, where it is not properly setting the provider based on the flag.

Using `kwil-cli configure`, my Kwil RPC provider URL is set to `http://localhost:8080`. If I try to set a URL via flag, it still uses this locally configured value:

```shell
$ kwil-cli utils ping provider=https://longhorn.kwil.com
Error: wrap client: chain_info: http post failed: Post "http://localhost:8080": dial tcp [::1]:8080: connect: connection refused
wrap client: chain_info: http post failed: Post "http://localhost:8080": dial tcp [::1]:8080: connect: connection refused
```

It does not use the provider set by my flag, which is the expected behavior.

**Comment by brennanjl** [comment]
I'm very dense and passed provider as an argument.

**Comment by jchappelow** [comment]
I'm adding `Args: cobra.NoArgs,` to commands like this so that it doesn't accept and ignore an extra argument in a confusion way like this.
