### ISSUE TITLE
Throwing Away Engine Error

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#725]
I noticed that with the addition of JSON RPC, we throw away engine errors if we do not know what they are, and simply return internal error. IMO this is bad; a lot of basic errors get discarded this way, including exceptions raised by the schema itself.

Is there a reason we are throwing them away?

**Comment by jchappelow** [comment]
I agree that's bad.  I didn't think we were throwing them away.

**Comment by brennanjl** [comment]
Here's where they are being thrown away: https://github.com/kwilteam/kwil-db/blob/f2850cfc0b54e2970e142ceec0424e36915e4b5a/internal/services/jsonrpc/usersvc/service.go#L313

**Comment by jchappelow** [comment]
Yeah.  Well, actually here: https://github.com/kwilteam/kwil-db/blob/f2850cfc0b54e2970e142ceec0424e36915e4b5a/internal/services/jsonrpc/usersvc/service.go#L310
