### ISSUE TITLE
Problem: Inconsistencies between procedures & foreign calls

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kwil-db#738]
One thing I just noticed:

The Kuneiform parser has a slight inconsistency in how it name returns from procedures versus foreign_calls. `procedures.return_types` versus `foreign_calls.returns`. Because these are both the same thing (`foreign_calls.returns` is just referencing the `procedures.return_types` on another schema), I think these should be consistent.

IMO, `procedures.return_types` and `foreign_calls.return_types` is good.

![Screen Shot 2024-05-14 at 6 38 31 PM](https://github.com/kwilteam/kwil-db/assets/105600466/05bd2e04-b191-40fe-9ea6-f9830e101639)

**Comment by brennanjl** [comment]
Was this addressed

**Comment by jchappelow** [comment]
I think it was good going to be with fffe109b3ada77f72e4a4ca48c8b3b042ea5e6d8b12e41d0bbdc3cadfe2d3239 but no more

**Comment by brennanjl** [comment]
Will add it to https://github.com/kwilteam/kwil-db/pull/794
