### ISSUE TITLE
Problem: Reader Starvation Impacts Consensus

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#755]
@pkoch saw consensus halt while running v0.7.2. We are fairly confident that this is because he also experienced reader starvation, which was due to failure to release read-only connections. @jchappelow fixed the release failure bug in https://github.com/kwilteam/kwil-db/pull/744, and it was included in v0.7.6.

While the root cause of the issue has been solved, it still highlights the potential for readers to slow down consensus, which should never be the case. In order to solve for this, all database connections in the consensus path should be readwrite connections. Below, I have linked all of the connections I can find in the consensus / proposal path that use reader connections:

- https://github.com/kwilteam/kwil-db/blob/553bb6f39c8ce6278c505d55ac08a80512e5ef4d/internal/txapp/txapp.go#L765
- https://github.com/kwilteam/kwil-db/blob/553bb6f39c8ce6278c505d55ac08a80512e5ef4d/internal/abci/abci.go#L231
- https://github.com/kwilteam/kwil-db/blob/553bb6f39c8ce6278c505d55ac08a80512e5ef4d/internal/abci/abci.go#L719
- https://github.com/kwilteam/kwil-db/blob/553bb6f39c8ce6278c505d55ac08a80512e5ef4d/internal/abci/abci.go#L849
- https://github.com/kwilteam/kwil-db/blob/553bb6f39c8ce6278c505d55ac08a80512e5ef4d/internal/voting/broadcast/broadcast.go#L92
- https://github.com/kwilteam/kwil-db/blob/553bb6f39c8ce6278c505d55ac08a80512e5ef4d/internal/voting/broadcast/broadcast.go#L137

These are pretty sneaky. I'm open to suggestions on how we could make the connection handling more obvious; the best thing I can think of is to handle creation of transactions in ABCI.

**Comment by jchappelow** [comment]
> These are pretty sneaky. I'm open to suggestions on how we could make the connection handling more obvious; the best thing I can think of is to handle creation of transactions in ABCI.

Right, we solved this sneakiness with explicit db transactions are function arguments, but we held onto the old design pattern with how ABCI uses TxApp.  I don't know if we want to make ABCI the transaction manager though.  Thinking about it.

>  Below, I have linked all of the connections I can find in the consensus / proposal path that use reader connections:

While the ones in proposal prepare or process aren't holding up block processing on non-validators, this is a problem too.

**Comment by jchappelow** [comment]
Can take a quick swing at resolving without refactoring large parts of abci and txapp.  Likely to be either extra methods or a `consensus bool` or something just to fix with minimal changes on 0.7 (well, on 0.8 too).
