### ISSUE TITLE
Bug: unexpected type in for loops

### ISSUE THREAD

**Issue by outerlook** [kwilteam/kwil-db#762]
### Version / Commit

current `main` branch

### Operating System

Ubuntu 22.04.4 LTS

### Configuration

none

### Expected Behavior

while trying to parse

```
database test;

procedure test() public {
    $values text[] := ['a', 'b'];

    $new_val text;
    for $row in $values {
        $new_val := $row;
    }
}
```

should work just fine

### Actual Behavior

I get 
```
(procedure) type error: text[] != text
start 8:9 end 8:25
```
it's specific to this line

```
$new_val := $row;
```

if you use `$new_val text[];` it works

### Steps to Reproduce

```
kwil-cli utils parse ./test.kf
```

### Additional Information

we know it's not even released yet :sweat_smile:

**Comment by outerlook** [comment]
Also, for additional context, the more real use case was this:
```
...
    $readonly_keys text[] := [
        'type',
        'stream_owner',
        'readonly_key',
        'taxonomy_version'
    ];

    for $key in $readonly_keys {
        $current_uuid := uuid_generate_v5($current_uuid, @txid);
        INSERT INTO metadata (row_id, metadata_key, value_s, created_at)
            VALUES ($current_uuid, 'readonly_key', $key, $current_block);
    }
...
```

**Comment by brennanjl** [comment]
Fixed: https://github.com/kwilteam/kwil-db/pull/765
