### ISSUE TITLE
Bug: unexpected result in procedure null comparison

### ISSUE THREAD

**Issue by outerlook** [kwilteam/kwil-db#763]
### Version / Commit

main branch

### Operating System

Ubuntu 22.04.4 LTS

### Configuration

none

### Expected Behavior

```
procedure test2() public view returns (result bool) {
    $value int;
    return $value == null;
}
```

Should return true, right? 

### Actual Behavior

I get 

```
| result |
+--------+
| <nil>  |
```

Or if I use this it's falsy

### Steps to Reproduce

```
kwil-cli utils parse ./test.kf
kwil-cli database deploy -n=test -p=./test_contract.kf
kwil-cli database call -n=test -a=test2
```

### Additional Information

this code gets compiled to the routine:
```
create function test2(OUT _out_0 boolean) returns boolean
	language plpgsql
as $$
DECLARE
_param_value INT8;
BEGIN
_out_0 := _param_value = NULL;
RETURN;

END;
$$;

alter function test2(out boolean) owner to kwild;
```

but `IS NULL` should be used instead of `= NULL`, right? 

Also, workarounds are easy, but create a hard to spot bug because it deploys successfully

**Comment by brennanjl** [comment]
Yes, you are correct. I'm a bit surprised it doesn't properly evaluate `_out_0 := _param_value = NULL;`. Will get this addressed.

**Comment by brennanjl** [comment]
So using `is` definitely works for null, but if we were doing any other data types (e.g. `_param_value = 0`), it gives the same behavior of an undefined result. Very annoying, working on a solution.

**Comment by brennanjl** [comment]
Fix is up here: https://github.com/kwilteam/kwil-db/pull/767
