### ISSUE TITLE
Bug: Network Migration from v0.7 to v0.8

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/kwil-db#780]
### Version / Commit

main

### Operating System

Darwin-Arm64

### Configuration

1. With a v0.7 node, I deploy the below schema and add a few records:

```
database spam_db;

table spam {
    id text primary notnull,
    message text notnull,
    time_created text notnull
}

action add_data ($id, $message, $time) public {
    INSERT INTO spam
    VALUES( $id, $message, $time);
}

action read_data () public view {
    SELECT * FROM spam LIMIT 35;
}
```

2. I follow the snapshot creation and migration process outlined [here](https://github.com/kwilteam/docs/pull/102).

3. I start a new node from the latest build on main with snapshotted data from v0.7.

### Expected Behavior

I ~think~ it should be able to start v0.8 with the old data seamlessly.

### Actual Behavior

Starting kwild on v0.8 (main) throws this error:

```
kwild version 0.8.0-pre+040e7cf6b (Go version go1.22.1)
Root directory "/Users/lukelamey/Documents/Github/kwil-db/.build/8-node"
Private key path: /Users/lukelamey/Documents/Github/kwil-db/.build/8-node/private_key
Snapshot file to initialize database from: /Users/lukelamey/Documents/Github/kwil-db/.build/8-node/kwildb-snapshot.sql
{"level":"info","ts":1717085736.448858,"logger":"kwild","caller":"statesync/statesync.go:202","msg":"Restore DB: ","command":"/opt/homebrew/bin/psql --username kwild --host 127.0.0.1 --port 5433 --dbname kwild --no-password"}
{"level":"info","ts":1717085736.606688,"logger":"kwild.pg","caller":"pg/db.go:117","msg":"Connected to PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit"}
{"level":"info","ts":1717085736.627444,"logger":"kwild.pg","caller":"pg/conn.go:123","msg":"NOTICE [00000]: Publication kwild_repl already exists."}
{"level":"info","ts":1717085736.6457741,"logger":"kwild.pg","caller":"pg/repl.go:109","msg":"Created logical replication slot kwild_replkbk27ady at LSN 0/1EA4840 (32131136)"}
{"level":"info","ts":1717085736.7089112,"logger":"kwild","caller":"server/build.go:321","msg":"closing main DB"}
Error: panic while building kwild: failed to initialize engine: failed to upgrade to version 1: unmarshaling schema: encoding/hex: invalid byte: U+006C 'l'

stack:

goroutine 1 [running]:
github.com/kwilteam/kwil-db/cmd/kwild/server.New.func1()
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/server/server.go:76 +0x1f4
panic({0x1037eca00?, 0x1400042aa20?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/panic.go:770 +0x124
github.com/kwilteam/kwil-db/cmd/kwild/server.failBuild(...)
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/server/build.go:905
github.com/kwilteam/kwil-db/cmd/kwild/server.buildEngine(0x14000641c80, 0x14000216780)
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/server/build.go:514 +0x630
github.com/kwilteam/kwil-db/cmd/kwild/server.buildServer(0x14000641c80, 0x14000111400)
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/server/build.go:175 +0x4c
github.com/kwilteam/kwil-db/cmd/kwild/server.New({0x103927088, 0x1400051a460}, 0x14000408660, 0x14000356230, 0x1400000eba0, 0x0)
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/server/server.go:115 +0x73c
github.com/kwilteam/kwil-db/cmd/kwild/root.RootCmd.func1(0x14000206908, {0x14000395400?, 0x7?, 0x1031e5f25?})
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/root/root.go:78 +0x328
github.com/spf13/cobra.(*Command).execute(0x14000206908, {0x1400004e060, 0x4, 0x4})
	/Users/lukelamey/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000206908)
	/Users/lukelamey/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(0x1400008c738?)
	/Users/lukelamey/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x1c
main.main()
	/Users/lukelamey/Documents/GitHub/kwil-db/cmd/kwild/main.go:11 +0x20
```

### Steps to Reproduce

Follow the configuration steps above.

### Additional Information

The migration process works fine from an old v0.8 network to a new v0.8 network, so I imagine this error has something to do with the schema changes between v0.7 and v0.8.

I am also not sure if we have agreed if network migration should be able to handle going from v0.7 to v0.8; however, after discussing with @charithabandi, I am adding this issue here so she can diagnose further.

**Comment by jchappelow** [comment]
> The migration process works fine from an old v0.8 network to a new v0.8 network, so I imagine this error has something to do with the schema changes between v0.7 and v0.8.

Ooof, yeah, this is a problem.  We have the schemas stored and loaded from `kwil_schemas` with:

```
sqlListSchemaContent = fmt.Sprintf(`SELECT schema_content FROM %s.kwil_schemas;`, pg.InternalSchemaName)
```

Then it unmarshals the bytes into a types.Schema.

I think 0.7 data is done now. :(

**Comment by jchappelow** [comment]
But more generally, why's it running a pg schema upgrade @charithabandi ?  Shouldn't it have brought over the version table?

**Comment by charithabandi** [comment]
Yeah, this is what bothers me. I need to check why the version upgrade is happening in the engine. We are not dropping the version tables from the internal schema.

![Screenshot 2024-05-30 at 11 31 14 AM](https://github.com/kwilteam/kwil-db/assets/45089429/dff0a7ee-34d2-417d-97a3-6e6be7d09364)

**Comment by charithabandi** [comment]
Interesting, there is a new schema version in v0.8. Which is causing the issue. Probably need correct upgrade procedures for v0-1

![Screenshot 2024-05-30 at 11 37 35 AM](https://github.com/kwilteam/kwil-db/assets/45089429/ffd7e1c9-33e7-44a5-977b-c42d47f5a51f)

**Comment by jchappelow** [comment]
Possibly we should have a version field of the schema type?  https://github.com/kwilteam/kwil-db/commit/3e000b5d06f99ac5081e2037fff98567628449e3
Going forward that could help if want to support multiple versions, or at least loading old versions in either kwild or just a migration tool.

We can detect the version without first hitting an unmarshal error by doing something like this:

```go

		var ver = struct {
			Version uint32 `json:"version"`
		}{}
		err := json.Unmarshal(bts, &ver)
		if err != nil {
			return nil, fmt.Errorf("unmarshaling schema for version: %w", err)
		}

	// Here we can use different types like SchemaV2 etc. based on ver above. (or jsut error informatively)

```

If we did update the kwil-admin snapshot functionality, it could recognize if it were snapshotting a certain version of a schema and migrate or not.

@brennanjl Not a solution on it's own, but something we might want in 0.8?
