### ISSUE TITLE
windows support for kwil-cli

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#796]
It is reasonable to offer a working Windows build of `kwil-cli` so end users on Windows can work with their data.

There's almost certainly a lot of baked in stuff with filepaths and posix conventions, but we can try.  e.g. "/" and "~" etc

`kwild.exe` is another thing to consider, but that's likely to require more work, and far less likely to have any use case.  (Windows Server is still a thing, somehow, but it's a small market share).

**Comment by brennanjl** [comment]
Eh, is there a good reason to though?

**Comment by jchappelow** [comment]
> Eh, is there a good reason to though?

Very possibly not.  Certainly server software (kwild) has less value with a Windows build.  Probably even `kwil-cli` would only every be used by infra providers rather than actual end users on their consumer devices.

**Comment by jchappelow** [comment]
@KwilLuke Thought on this since we talked in Slack?  Was there a particular org that asked for this or hinted Windows on either server or user side would be needed?  We can close and reopen this later if needed.

**Comment by KwilLuke** [comment]
@jchappelow - let's close for now. We can re-open once it comes up with a partner.
