### ISSUE TITLE
Feature: Block data in extensions

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#821]
In `TxApp` routes, we are able to access block info (height, proposer, consensus params, etc). We should also be able to access these within action and resolution extensions, since these are simply extensions extending execution logic of a block.

This would be a breaking changes, so it cannot come until v0.9.

**Comment by jchappelow** [comment]
I think this can be done without breaking the Go APIs (adding fields and methods isn't breaking to Go consumers).

For action extensions, we can add fields to `extensions/precompiles.ProcedureContext`.  Only removing or changing existing fields and methods would be a problem.  If an extension wants to use added features in v0.8.2 (for example), they simple require at least v0.8.2.

For resolutions, there are some options too, I believe:

- add a new field to `ResolutionConfig` that specifies a context-aware method to use _instead of_ `ResolveFunc`
- Use the existing `context.Context` passed to `ResolveFunc` using `context.WithValue` and some exported context *key* that ensures that if the extension builds while referencing that exported key variable then `kwil-db` will be providing that contextual data in the value retrieved with that context key.

**Comment by brennanjl** [comment]
Looping back to this because I need it for migrations.

```
Use the existing context.Context passed to ResolveFunc using context.WithValue and some exported context key that ensures that if the extension builds while referencing that exported key variable then kwil-db will be providing that contextual data in the value retrieved with that context key.
```

Would you consider this to be a generally good solution, as opposed to custom context structs? We don't rely much on `context.Context` right now, but it seems like it could solve some of these problems for us. Keep in mind that we can use a breaking change for this, since it is v0.9

**Comment by jchappelow** [comment]
Just discussed in person, but this std lib context solution is fine IMO (that's what it's designed for) but really not worth the acrobatics and confusion unless keeping the function signature the same is critical.  A custom "context" that has a standard lib context as a field among other obviously enumerated fields seems just fine if changing `ResolveFunc` is not a problem.

**Comment by brennanjl** [comment]
Resolved by https://github.com/kwilteam/kwil-db/commit/dd5719a7b8f16949375d06a782aa646d30f6d165#diff-a70f47b70b2d542f3eaa01a097d0f6d97e1f49cee567e258d4afc2a79f07af92

**Comment by brennanjl** [comment]
Resolved by https://github.com/kwilteam/kwil-db/pull/831
