### ISSUE TITLE
integration test: create tests for state sync and genesis_state

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#834]
integration tests needed:

- fresh chain with no genesis state and with null app_hash, `app.snapshots.enabled=true`, then a joining node at block X (say 10) that uses statesync
- basic migration / genesis state: start a chain with genesis_state set to some gzip (maybe we create it or maybe the test has a preparation stage), make sure all genesis validator nodes run without app hash mismatch, then add a new node that uses statesync (doesn't actually need the gzip file).  Variation: the joining node could be a minority validator that is just hopping on the network late.

**Comment by charithabandi** [comment]
https://github.com/kwilteam/kwil-db/pull/887 added as part of this
