### ISSUE TITLE
apphash mismatch on every restart of node (in network)

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#843]
Given a network with at least two nodes (one can be sentry), you always get an apphash mismatch after restarting the node.

This is because we fail to load the apphash from the chain state db in the `AbciApp` constructor.  Previously this was done in `TxApp`'s constructor, but that was moved to ABCI in https://github.com/kwilteam/kwil-db/pull/831.  A `git bisect` confirms that's the cause.

Assigning myself.  Fix in preparation.

**Comment by brennanjl** [comment]
Oh man, good catch. Sorry about that

**Comment by jchappelow** [comment]
Was a really minor thing.  Hard to automatically test stuff like this where restarts are involved, hence why I messed up the consensus parameters storage issue in the first place.  :(
