### ISSUE TITLE
node cannot sync if network has no snapshots

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#890]
If you try to sync a node with `chain.statesync.enable` but there are no snapshots on the network yet, it hangs forever.  You have to disable.

**Comment by charithabandi** [comment]
Yeah, this is documented behavior for statesync. We probably need our snapshot provider to snapshot as soon as it boots up, so that it can support snapshotting right off the bat.

**Comment by jchappelow** [comment]
We should make an issue with cometbft for a fallback to blocksync option.  But I agree that a node should create a snapshot if:

- none exists
- it is height 1 (genesis+1)

**Comment by charithabandi** [comment]
https://github.com/cometbft/cometbft/issues/3878 Raised an issue with cometbft for switching to blocksync mode.
