### ISSUE TITLE
core: remove PayloadTypeCallAction 

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kwil-db#904]
`PayloadTypeCallAction` is misleading, since `PayloadType` is only used in transaction, and 'call' an action is not a transaction

**Comment by jchappelow** [comment]
That totally threw me off too.  I don't see a reason why `CallAction` has to satisfy the `Payload` interface.  As you said it's never in a transaction and `transactions.UnmarshalPayload` won't need to be able to unmarshal it.

**Comment by jchappelow** [comment]
Will look into this today.
