### ISSUE TITLE
migration issues

### ISSUE THREAD

**Issue by jchappelow** [kwilteam/kwil-db#952]
We attempted a zdt migration and ran into some issues.  A few of these affect regular stop-and-start migrations, so listing here to make sure they are addressed:

- [x] migration type resolutions almost certainly should be removed in either type of migration (zdt or offline)
- [x] on the new network, another migration should not be allowed to start before the previous migration is completed.
- [x] resolution expirations have an expiry height column that is incorrect
- [x] because the validator set can change, pending resolution can suddenly become approved/finalized on the first block (conversely, some resolutions may actually "lose" their approving validators, which could be a non-issue)
- [x] I started the one node of the new network the first time with an empty `migrate_from`, so it didn't start the migration listener, which is expected, however, genesis.json had a `"migration"` so the node just sat there.  Should / can we shut it down instead?  This is a non-workable config.
- [x] The `migrate propose` command wrote out a `genesis.json` with `"without_gas_costs": true`, but the original network had `"without_gas_costs": false`.  What other flags are being reset to defaults?
- [x] The `migrate status` and `migrate list` command only pertain to pending (not yet approved) migrations. Once they are approved, there is no way to determine the status of a migration.  It could be awaiting it's activation/start height, or it could be in migration and generating/transmitting changesets, or it could have reached end and halted the chain.  This is begin documented behavior, but surprising.
- [x] `kwil-admin node status` should probably have a field(s) to indicate if the network is in a migration, and another if it has halted, perhaps even list migration status.
- [x] When the nodes on the old network reached the end height, they both correctly halted (`NETWORK HALTED: migration to chain "staging-migrated0" has completed`), but they did not shutdown.  This actually made some sense to me as (read-only) RPCs should still be usable and maybe other uses.  However, after stopping one, I could not start it again.  (`failed to build comet node: failed to create CometBFT node: error during handshake: error on replay: failed to notify migrator of changeset: NETWORK HALTED: migration to chain "staging-migrated0" has completed`).  I think the consensus failure prior to stopping actually should have shut it down.
- [x] Should be able to resubmit migration proposals with the same migration params after expiry. Add, timestamp to make the migration proposals unique. 
- [x] Optimize changesets listener to maybe not submit empty resolutions to the vote store for blocks that have no changesets? This is to avoid heavy load on the system due to the vote store consensus mechanism for empty resolutions.
- [x] Rethink the chunking process of changesets. The chunks should be less than the blocksizes of the new network, if the new network starts with the lower blocksize, these chunks can't fit in a transaction.

**Comment by brennanjl** [comment]
> I started the the one node of the new network the first time with an empty migrate_from, so it didn't start the migration listener, which is expected, however, genesis.json had a "migration" so the node just sat there. Should / can we shut it down instead? This is a non-workable config.

Yes. This is possible, however it requires a minor change to add the node's full config to the `common.Service` struct. I was planning on making this change before the beta because I have twice now run into instances where I felt we should be able to access this info. Will put up a PR for this shortly.

> I started the the one node of the new network the first time with an empty migrate_from, so it didn't start the migration listener, which is expected, however, genesis.json had a "migration" so the node just sat there. Should / can we shut it down instead? This is a non-workable config.

This seems correct to me. IMO, it should keep the same `without_gas_costs` config as the old network. To answer the question, here is our genesis config (defined in `common/chain/chaincfg.go`), with comments explaining what I _think_ should happen for each config (but I am open to other ideas):

```go
type GenesisConfig struct {
	GenesisTime   time.Time  // should be set to the block timestamp at which the migration resolution passes
	ChainID       string // should be set to the new chain ID
	InitialHeight int64 // should be set to the height at which the new network starts / migration resolution passes
	DataAppHash   []byte // should be based off of the genesis snapshot
	Alloc         GenesisAlloc // should be empty since we transfer all balances as part of the snapshot
	ForkHeights map[string]*uint64  // Any height that is greater than the new InitialHeight should be kept, the rest can be forgotten
	ConsensusParams *ConsensusParams // these should all be the same except for ConsensusParams.BaseConsensusParams.Migration, which should be new for this migration
	Validators      []*GenesisValidator // these should be based off of the approvers of the migration? I am not too sure here
}
```

CC @charithabandi would be good to get your thoughts here. As a side note, it seems like we can get rid of `BaseConsensusParams`, and just have a `ConsensusParams` struct

> The migrate status and migrate list command only pertain to pending (not yet approved) migrations. Once they are approved, there is no way to determine the status of a migration. It could be awaiting it's activation/start height, or it could be in migration and generating/transmitting changesets, or it could have reached end and halted the chain.

Seems like `migrate status` should return information on an active (already approved) or completed migration.

> When the nodes on the old network reached the end height, they both correctly halted (NETWORK HALTED: migration to chain "staging-migrated0" has completed), but they did not shutdown. This actually made some sense to me as (read-only) RPCs should still be usable and maybe other uses. However, after stopping one, I could not start it again. (failed to build comet node: failed to create CometBFT node: error during handshake: error on replay: failed to notify migrator of changeset: NETWORK HALTED: migration to chain "staging-migrated0" has completed). I think the consensus failure prior to stopping actually should have shut it down.

IMO the _ideal_ solution would be that the old node stays running to respond to RPC requests, but if this is hard to implement, I think it is ok to just have it shut down.

**Comment by jchappelow** [comment]
> This seems correct to me. IMO, it should keep the same `without_gas_costs` config as the old network

This is a typo in the issue, now edited.  I went from false to true.

**Comment by charithabandi** [comment]
because the validator set can change, pending resolution can suddenly become approved/finalized on the first block (conversely, some resolutions may actually "lose" their approving validators, which could be a non-issue) 

Is there anything we should do here?

**Comment by jchappelow** [comment]
> because the validator set can change, pending resolution can suddenly become approved/finalized on the first block (conversely, some resolutions may actually "lose" their approving validators, which could be a non-issue)
> 
> Is there anything we should do here?

We chatted in person, but I think we decided if the only resolutions we allow to pass in the genesis-purposed snapshot are account credits / deposits, then there's no issue.

**Comment by brennanjl** [comment]
> We chatted in person, but I think we decided if the only resolutions we allow to pass in the genesis-purposed snapshot are account credits / deposits, then there's no issue.

I think we should allow _any_ resolution except for network migrations and validator approvals, right?
