### ISSUE TITLE
Remove `app.snapshot.max_row_size`

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#983]
We have this `app.snapshot.max_row_size`, which sets a max row size for snapshots. This can very easily be attacked, by any end-user submitting a huge payload, thus breaking snapshots for all nodes. Kwil should be able to support arbitrary sized rows for snapshots.

**Comment by brennanjl** [comment]
FYI @charithabandi we should make sure to remove this as well: https://github.com/kwilteam/kwil-db/blob/e6922733fc1a7a80c90297b17402db90a8e1235f/cmd/kwil-admin/cmds/snapshot/create.go#L86

**Comment by charithabandi** [comment]
> FYI @charithabandi we should make sure to remove this as well:
> 
> https://github.com/kwilteam/kwil-db/blob/e6922733fc1a7a80c90297b17402db90a8e1235f/cmd/kwil-admin/cmds/snapshot/create.go#L86

Yup, marked to be deprecated it in the PR
