### ISSUE TITLE
`app.tls_cert_file` and `app.tls_key_file` are incorrectly documented

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/kwil-db#999]
The `app.tls_cert_file` and `app.tls_key_file` configs are not correctly documented, and should be renamed.

Previously, these configs allowed users to configure TLS for all of the RPCs provided by Kwil. However, when we moved the user service to JSON RPC, we removed the ability to configure TLS, since most users should just use nginx anyways. Now, the TLS configs only apply to the admin service and to comet BFT's RPC (which I am not sure why we ever had it do that in the first place).

Therefore, there are 3 changes we need to make:
- [ ] rename the configs to be `app.admin_tls_cert_file` and `app.admin_tls_key_file`
- [ ] remove the ability for these to be used to configure CometBFT's RPC
- [ ] update the [documentation](<https://github.com/kwilteam/docs>) to make it clear these are only for admin

**Comment by jchappelow** [comment]
Doing this.  Assuming you don't have this already done @brennanjl ?

**Comment by brennanjl** [comment]
I have not done this yet. Thanks.
